name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - khem/cicd-integration

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  REGISTRY_HOST: https://asia.gcr.io
  PROJECT_ID: incomi
  REGISTRY_URL: $REGISTRY_HOST/$PROJECT_ID

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Run tests
  #       run: |
  #         if [ -f docker-compose.test.yml ]; then
  #           docker-compose --file docker-compose.test.yml build
  #           docker-compose --file docker-compose.test.yml run sut
  #         else
  #           docker build . --file Dockerfile
  #         fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      
      - name: Build frontend as static HTML files using nuxt generate
        working-directory: ./nuxt/src/app
        uses: actions/setup-node@v1
        with:
          node-version: '12'
        run: |
          yarn install
          yarn run generate
      
      - name: Deploy frontend to Firebase
        working-directory: ./nuxt/src/app
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Build images
        run: docker-compose -f docker-compose-prod.yml build 

      - name: Log into Google Container Registry
      # Create a Service Account with the "Storage Admin" role and put the JSON key of the account in a secret called "GCR_JSON"
        run: echo "${{ secrets.GCR_JSON }}" | docker login $REGISTRY_HOST -u _json_key --password-stdin

      - name: Push image to Google Container Registry
        run: docker-compose push
      
      - name: Log in to the virtual machine on GCP
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al

          